name: Deploy Springboot App to EC2

on:
  push:
    branches:
      - deploy-to-ec2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Amazon ECR
        id: ecr_login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t avoworld:latest .

      - name: Tag Docker image
        run: docker tag avoworld:latest ${{ secrets.ECR_URL }}/avoworld:latest

      - name: Push Docker image to ECR
        run: docker push ${{ secrets.ECR_URL }}/avoworld:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Decode and save keystore
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > keystore.p12

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}
            
            # Pull the latest Docker image from ECR
            docker pull ${{ secrets.ECR_URL }}/avoworld:latest

            # Stop the existing container if it's running
            docker stop avoworld || true

            # Remove the existing container if it exists
            docker rm avoworld || true

            # Run a new container with the updated image
            docker run -d --name avoworld -p 8443:8443 \
              -e DB_URL=${{ secrets.DB_URL }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -e JWT_KEY=${{ secrets.JWT_KEY }} \
              -e AWS_S3_REGION=${{ secrets.AWS_REGION }} \
              -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
              -e AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} \
              -e S3_BUCKET=${{ secrets.S3_BUCKET }} \
              -e KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} \
              -e KEYSTORE_ALIAS=${{ secrets.KEYSTORE_ALIAS }} \
              -v $(pwd)/keystore.p12:/app/keystore.p12 \
              ${{ secrets.ECR_URL }}/avoworld:latest
